version: "3.8"
services:
  reverseproxy:
    image: $DOCKER_USERNAME/udagram-reverse-proxy:latest
    ports: 
      - 8080:8080
    depends_on:
      - feed-service
      - user-service
  user-service:
    image: $DOCKER_USERNAME/user-service:latest
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      JWT_SECRET: $JWT_SECRET
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWSMEDIABUCKET: $AWSMEDIABUCKET
      URL: "http://localhost:8100"
  feed-service:
    image: $DOCKER_USERNAME/feed-service:latest
    volumes:
      - ${HOME}/.aws:/root/.aws
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      JWT_SECRET: $JWT_SECRET
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWSMEDIABUCKET: $AWSMEDIABUCKET
      URL: "http://localhost:8100"
  front-end-service:
    image: $DOCKER_USERNAME/front-end-service:latest
    ports:
      - "8100:80"