version: "3.8"
services:
  reverseproxy:
    build:
      context: .
    image: $DOCKER_USERNAME/udagram-reverse-proxy:latest
  user-service:
    build:
      context: ../user-service
    image: $DOCKER_USERNAME/user-service:latest
  feed-service:
    build:
      context: ../feed-service
    image: $DOCKER_USERNAME/feed-service:latest
  front-end-service:
    build:
      context: ../front-end-service
    image: $DOCKER_USERNAME/front-end-service:latest