apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
    tier: backend-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
selector:
  app: user
  tier: backend-service
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels: 
      app: user
      tier: backend-service
  replicas: 2
  template:
    metadata:
      labels:
        app: user
        tier: backend-service
    spec:
      containers:
      - name: user-service
        image: kufrank81/user-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
  labels:
    app: feed
    tier: backend-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
selector:
  app: feed
  tier: backend-service
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: feed-service
spec:
  selector:
    matchLabels: 
      app: feed
      tier: backend-service
  replicas: 2
  template:
    metadata:
      labels:
        app: feed
        tier: backend-service
    spec:
      containers:
      - name: feed-service
        image: kufrank81/feed-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    app: front-end
    tier: front-end-service
spec:
  ports:
  - port: 8100
    targetPort: 8100
selector:
  app: front-end
  tier: front-end-service
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: front-end-service
spec:
  selector:
    matchLabels: 
      app: front-end
      tier: front-end-service
  replicas: 2
  template:
    metadata:
      labels:
        app: front-end
        tier: front-end-service
    spec:
      containers:
      - name: front-end-service
        image: kufrank81/front-end-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
    tier: proxy-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: kufrank81/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always